import { Plant } from './types';

export const INITIAL_PLANTS: Plant[] = [
  {
    id: 'monstera-deliciosa',
    name: 'Monty',
    species: 'Monstera Deliciosa',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuASAxs0DDWrz9ZNYV5xzP0BTKaRPrHhCohAj4vGqJBKWc4t6uEtgooFInHVrFD_WXYsDkPb4QjyNTDkSpjKxu3-S3CkED8mizyL2KGYT13ICyx05Qtnwq4p5Es6Cszf_02wi-dFELUz4-EwYYaEZixDXvl7LCg_RVUxp3KyRmD7FNTMwfl9tFgqbsBoqvF0Ax2_TmfqpEfmNDFHaUhL_wVvXOuTJF5dSnjBtK5O44lOqH0vB8ZFY1hE',
    thirstLevel: 3,
    difficulty: 'medium',
    streak: 45,
    location: 'Living Room',
    about: 'A beautiful tropical aroid native to southern Mexico and Panama. Known for its natural leaf holes, these unique fenestrations allow light to pass through to lower leaves in its native dense jungle habitat. Thrives in warm, humid environments.',
    tags: ['Bright Indirect Light', 'Toxic to Pets'],
    status: 'alive',
    lastWatered: new Date().toISOString(),
    createdAt: '2025-05-15T08:00:00.000Z',
    careHistory: [
      {
        id: 'c1',
        date: 'Today',
        time: '9:00 AM',
        title: 'Watered thoroughly.',
        description: 'Soil was dry to touch.',
        type: 'water',
      },
      {
        id: 'c2',
        date: 'Oct 12, 2023',
        title: 'Applied liquid fertilizer (half strength).',
        description: 'Monthly feeding.',
        type: 'fertilize',
      },
      {
        id: 'c3',
        date: 'Oct 5, 2023',
        title: 'Rotated pot 90 degrees for even growth. Wiped down leaves with a damp cloth.',
        description: 'Removed ambient dust to help photosynthesis.',
        type: 'note',
      },
    ],
  },
  {
    id: 'string-of-pearls-live',
    name: 'Pearls',
    species: 'String of Pearls',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCwNxNVS4UwhrsSIu2IHLwR46hemYe9l09J2NaLr5ZeTowQNjf1hX7QEwGbebxzefINmm3rLjP6vpdmyp7WjImZxvW7R4EIYwxaJuLPaXcVeP4n1BQqdbOJhj0wlebZFVQA0mopjxTGnb0rhWfYzjzGmOMwK0sleqKJmKiH4xbcSLUOgb84s2eaeBP-UHUcr99linzPoH_NTN4n1PzZkZzidF0IRUUnvC9BD-IJy1puPUUb8o16xxXR',
    thirstLevel: 1,
    difficulty: 'easy',
    streak: 8,
    location: 'Bedroom Window',
    about: 'Senecio rowleyanus is a creeping, perennial, succulent vine belonging to the family Asteraceae. Its trailing vines with green sphere "pearl" leaves make it highly coveted.',
    tags: ['Bright Direct Light', 'Toxic to Pets'],
    status: 'alive',
    lastWatered: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: '2026-06-01T08:00:00.000Z',
    careHistory: [
      {
        id: 'cp1',
        date: '3 days ago',
        title: 'Watered lightly.',
        description: 'Soil was bone dry.',
        type: 'water',
      },
    ],
  },
  {
    id: 'fiddle-leaf-fig-live',
    name: 'Fiona',
    species: 'Fiddle Leaf Fig',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC2lAiAJU-eCHOTQGJnFCP3FG93bfUBINQVjDDfbTlNsl2gKJSnA4llPkkyC0x0o7svCvk4NjKH0JidOt6cSQdo_z6uAiMTm6CVCpu7atQzYUJv-8CLeiSnI1pMB71B0G_hrUzYLQFMYxXE8IoGgajfJ5uHTKp-7fl_wSC6DIqtRJWxfsddCRcf_Q2756ws9WCE1S-Fjzs-zIbZnEdv5NetC2pKi_U4AWDSZqvSX4irfEFUg2yu7XRL',
    thirstLevel: 3,
    difficulty: 'hard',
    streak: 12,
    location: 'Living Room Corner',
    about: 'Ficus lyrata, commonly known as the fiddle-leaf fig, is a species of flowering plant in the mulberry and fig family Moraceae. It is notorious for being sensitive to drafts and shifts in light.',
    tags: ['Bright Indirect Light', 'Sensitive to Drafts'],
    status: 'alive',
    lastWatered: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(), // Needs watering today!
    createdAt: '2026-05-10T10:00:00.000Z',
    careHistory: [
      {
        id: 'ff1',
        date: '8 days ago',
        title: 'Watered thoroughly.',
        description: 'Needs watering soon.',
        type: 'water',
      },
    ],
  },
  {
    id: 'golden-pothos-live',
    name: 'Aurelia',
    species: 'Golden Pothos',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA0H75nk--sL-omGzmKDT-iluOPzvM2gA88htxH1B3eCp7APGx81egeiZMWie7RCAqOwd_kHj3uWo33yxvKmN1uWNud1OngFpSDRnhcS7xdInXxufyVs85620m4BDPGNdedAQoU3Ddnr2by8pNNa8HVs69cflnaqVv5UGoxnP_NSmbQRMiaDJBmGkpCbrqRt_-QzH7urbpK9ouQgFFyUkg2i-Sd_PRO2vAaDx8CJT0O5YtdSPe5ADI8',
    thirstLevel: 4,
    difficulty: 'easy',
    streak: 30,
    location: 'Kitchen Shelves',
    about: 'Epipremnum aureum is a species of flowering plant in the arum family Araceae, native to French Polynesia. Known as the devil\'s ivy because it is almost impossible to kill and it stays green even when kept in the dark.',
    tags: ['Low to Medium Light', 'Easy Care'],
    status: 'alive',
    lastWatered: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(), // Medium dry
    createdAt: '2026-02-14T11:00:00.000Z',
    careHistory: [
      {
        id: 'gp1',
        date: '6 days ago',
        title: 'Watered till runoff.',
        description: 'Soil is moderately dry.',
        type: 'water',
      },
    ],
  },
  {
    id: 'aloe-vera-live',
    name: 'Vera',
    species: 'Aloe Vera',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuARHj5oajzjv1Goxyxfvj0fux4KqMH9erZjxyUAUE5ZQxdi7dBNVWSddXTvlGaxe2bThK144-5scNa_Ok2uiFI1NXl2Ey8xUIK8qhWYNscngkz9f1OqQwCKivcGGGM0PtY3QCKmBmSF6Jthtp3nbYggwehJ8W3mdV70kfcuepNQoASzfTd_89Q77tLWxWJqcXc6GhlUIp3ncIF-bwQxuT2E21tQH9rHs7PAfS7KZh57KLXywnlfMF7e',
    thirstLevel: 2,
    difficulty: 'easy',
    streak: 19,
    location: 'Office Desk',
    about: 'Aloe vera is a succulent plant species of the genus Aloe. Having been used for centuries as a medicinal ointment, it thrives on bright sunlight and very little watering.',
    tags: ['Bright Direct Light', 'Healing Sap'],
    status: 'alive',
    lastWatered: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: '2026-03-20T09:00:00.000Z',
    careHistory: [
      {
        id: 'av1',
        date: '14 days ago',
        title: 'Watered deeply.',
        description: 'Likes dry soil.',
        type: 'water',
      },
    ],
  },
  {
    id: 'snake-plant-live',
    name: 'Zul',
    species: 'Snake Plant',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD_DCJ-InFwhqd1rTLr9FMHrg3z3M5Z3RWHRLEtPBUeNR9DIjWuFb5o9J1FS91JY4LxW7KGJBIBInrZExQ6P_U2XNALUfBW6P2cxweFAdDC-j-t3dHUVQaMxosEzjnBA0pDekQLdWJQXjNssRKCo8KXknka0DSWHbuP3jsBn45TBYhoxPL4SAQQDl5R9IFSZitsa3ecCx-sLWXfFjP-mRVYfh9WeS8aNzB30sDlAEI0DziBlcuK5kxl',
    thirstLevel: 2,
    difficulty: 'easy',
    streak: 62,
    location: 'Hallway',
    about: 'Dracaena trifasciata is a species of flowering plant in the family Asparagaceae, native to tropical West Africa. It is extremely tolerant of neglect and low light levels, acting as a natural air purifier.',
    tags: ['Low Light Tolerant', 'Clean Air'],
    status: 'alive',
    lastWatered: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: '2025-10-01T14:00:00.000Z',
    careHistory: [
      {
        id: 'sp1',
        date: '12 days ago',
        title: 'Gave a glass of water.',
        description: 'Loves ignoring.',
        type: 'water',
      },
    ],
  },
  
  // GRAVEYARD PLANTS
  {
    id: 'graveyard-fiddle-leaf-fig',
    name: 'Fiddle Leaf Fig',
    species: 'Fiddle Leaf Fig',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBXeKdWkb8ASaImTyn_vghVk4fzk30vdms9RjsXDJwJdeozWqLWULC7HUk1DJ9arhDg2R7KvvOrJUP0CQnd4TO7l_4SqGVIlz-ZNwLys_2O07tBWXZyzCI_cy2MG7YfrktjpHwZr6eGyXMswGZ8q6Gij-HBxprPe8rtymITZ2R_CnCBr9fYBdLcY9tYi1FMot5WgKJA6PKY2P-7Y9VS3xbidH1-w2hcYcykUcsN0E7tj_LyEbqOsoyd',
    thirstLevel: 3,
    difficulty: 'hard',
    streak: 0,
    location: 'Drafty Entrance Window',
    about: 'Our first attempts with a Fiddle Leaf Fig. It suffered from root rot and draft exposure.',
    tags: ['Draft Sensitive'],
    status: 'dead',
    lastWatered: '2023-11-01T09:00:00.000Z',
    createdAt: '2021-08-10T09:00:00.000Z',
    livedDuration: '2 Years, 3 Months',
    memoryNote: '"Remembered Fondly. You fought bravely against the drafts, but the winter was too harsh."',
    careHistory: [],
  },
  {
    id: 'graveyard-calathea-ornata',
    name: 'Calathea Ornata',
    species: 'Calathea Ornata',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDZh3WT1Px6j3d_eMyKw7vx_cH5vA48YRmQZVcKs21f_iGW1xEmiOwZVFlOKLDtBU_TSNbWUwTyA9sOUJWq8wUSkS1D4JkQDf0sB5321hTj6JQo3x_8jybOfxTAazDMB4PoXnpxEuQ26iOgS7h41SMjrLQILbbPdvIbPe6WDiEct314BCAXjAEyXyCrxe8OICOEORnnMUN52S42q2ARIfCNiSZf5rTXKRfwkqpFFWJbuA81y0MDN1Sh',
    thirstLevel: 4,
    difficulty: 'hard',
    streak: 0,
    location: 'Bathroom Shelf',
    about: 'A notoriously dramatic plant that dried up because of insufficient humidity levels.',
    tags: ['Drama Queen', 'Humidity Loving'],
    status: 'dead',
    lastWatered: '2023-04-12T09:00:00.000Z',
    createdAt: '2022-08-12T09:00:00.000Z',
    livedDuration: '8 Months',
    memoryNote: '"Gone but not Forgotten. The crisp edges were just a sign you wanted to be closer to the sun."',
    careHistory: [],
  },
  {
    id: 'graveyard-string-of-pearls',
    name: 'String of Pearls',
    species: 'String of Pearls',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAyPqb2P0YjThCqvcSSJfIkMrIETzhjemVkbBc5ZdW1aJSKzaGefRGYgbFz1eFNEB0eWYcGSSdHlQlwmFeZp-28k_-4RMl5_P4DiSo0ivEHxGu-TPkei_F4acUACFaI2tYx60fnsut4r9nms5QHcHHxbxn22Xd6p_UGIXTC_FFVl-dMDCira4IlSDEvOAkUQEaul_Itt4ghw22jZ1MKOuXqMytnCXUtTPN92XpcuASnfwMZ5KOJ7oeR',
    thirstLevel: 1,
    difficulty: 'easy',
    streak: 0,
    location: 'Study Desk',
    about: 'Our tiny trailing pearl plant. It was watered too frequently and collapsed due to root rot.',
    tags: ['Cactus Care'],
    status: 'dead',
    lastWatered: '2023-10-05T09:00:00.000Z',
    createdAt: '2022-09-05T09:00:00.000Z',
    livedDuration: '1 Year, 1 Month',
    memoryNote: '"Rest in Peace. I over-loved you with water, a lesson learned the hard way."',
    careHistory: [],
  },
];
